<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <!-- Fontfaces CSS-->
    <link href="css/font-face.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/theme.css" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
   
        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->
       <!-- MENU SIDEBAR-->
        <?php include('sidebar.php'); ?>
        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <?php include('header.php'); ?>
        
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                   
                       

                       <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>



                        <div class="row">
                            <div class="col-lg-12">
                                <h2 class="title-1 m-b-25">Nouvel article</h2>
                                <div class="table-responsive table--no-card m-b-40">

                                   <table id="example" class="display" style="width:100%">
                                        <thead>
                                            <tr>                                        
                                                <th>Titre</th>
                                                <th>article</th>
                                                <th>Image</th>
                                                <th>Date</th>
                                                <th>Auteur</th>           
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach($apost as $post): ?>
                                            <tr>
                                                <td><?= $post['Title'] ?></td>
                                                <td><?= substr($post['Content'], 0, 31).' [...]' ?></td>
                                                <td><img src="../<?= $post['Image'] ?>" style="height: 25px;"></td>
                                                <td><?= $post['CreationTimeStamp'] ?></td>
                                                <td><?= $post['Author'] ?></td>  
                                            </tr>
                                            <?php endforeach; ?>    
                                        </tbody>
                                    </table>
                                    <div class="col-lg-12">
                                <div class="card" style="margin-top: 25px;" >
                                    <div class="card-header">
                                        <strong>Nouvel</strong> Article
                                    </div>
                                    <div class="card-body card-block">
                                        <form action="add_post.php" method="post" enctype="multipart/form-data" class="form-horizontal">
                                        <div class="row">
                                            <div>
                                                <div class="form-group">
                                                    <div class="col col-md-3">
                                                        <label for="text-input" class=" form-control-label">Titre</label>
                                                    </div>
                                                    <div class="col-12 col-md-12">
                                                        <input type="text" id="text-input" name="Title" placeholder="Text" class="form-control">
                                                    </div>
                                                </div> 
                                                    <div class="col col-md-3">
                                                        <label for="text-input" class=" form-control-label">Dates</label>
                                                    </div>
                                                    <div class="col-12 col-md-12">
                                                        <input type="text" id="text-input" name="CreationTimeStamp" placeholder="Text" class="form-control">
                                                    </div>
                                            </div> 
                                            <div class="form-group col-3 col-md-7">
                                                <div class="col col-md-3">
                                                    <label for="textarea-input" class=" form-control-label">Contenu</label>
                                                </div>                                 
                                                <div class="col-3 col-md-12">
                                                    <textarea name="Content" id="textarea-input" rows="5" placeholder="Contenu" class="form-control"></textarea>
                                                </div>
                                            </div>
                                    </div>
                                    <div class="row">
                                            <div>
                                                <div class="form-group">
                                                    <div class="col col-md-6">
                                                        <label for="text-input" class=" form-control-label">Auteur</label>
                                                    </div>
                                                    <div class="col-12 col-md-12">
                                                        <input type="text" id="text-input" name="Author" placeholder="Text" class="form-control">
                                                    </div>
                                                </div>                                  
                                            </div>                                     
                                    </div>                                     
                                            <div class="row form-group">
                                                <div class="col col-md-2">
                                                    <label for="file-input" class=" form-control-label">File input</label>
                                                </div>

                                                <div class="col-12 col-md-9">
                                                    <input type="hidden" id="file-input" name="" class="form-control-file">
                                                    <input type="text" name="Image" class="form-control">
                                                </div>
                                                <input type="hidden" name="Places_nbr" value="1">
                                                <input type="hidden" name="PostState" value="1">
                                            </div>
                                            <div class="card-footer">
                                            <button type="submit" class="btn btn-primary btn-sm">
                                                <i class="fa fa-dot-circle-o"></i> Envoyer
                                            </button>
                                            <button type="reset" class="btn btn-danger btn-sm">
                                                <i class="fa fa-ban"></i> Reset
                                            </button>
                                    </div>

                                        </form>
                                    </div>                                    
                                </div>
                                <div class="card">
                                </div>
                            </div>
                                </div>
                            </div>
                           
<script type="text/javascript">
    
    $(document).ready(function() {
    $('#example').DataTable();
} );
</script>
                        
                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>

    <!-- Jquery JS-->

    <!-- Bootstrap JS-->
    <script src="vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="vendor/slick/slick.min.js">
    </script>
    <script src="vendor/wow/wow.min.js"></script>
    <script src="vendor/animsition/animsition.min.js"></script>
    <script src="vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="vendor/circle-progress/circle-progress.min.js"></script>
    <script src="vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="js/main.js"></script>

</body>

</html>
<!-- end document-->
